### ISSUE TITLE
Create docs for each release

### ISSUE THREAD

**Issue by pauldendulk** [Mapsui/Mapsui#1561]
Currently there is only one documentation set which corresponds to current master (beta v4, not v3). We should push separate documentation sets for each release. To support v3 we should push docs from develop/3.x into a separate folder.

**Comment by pauldendulk** [comment]
I implemented this by deploying from both branches with `peaceiris/actions-gh-pages` and `keep_files: true`.

```yaml
    - name: Upload artifact
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./website
        destination_dir: v5
        keep_files: true
```
